theme: jekyll-theme-minimal
title: PocketDocs
description: PocketDocs é uma iniciativa de produção audiovisual para as Redes Sociais, espaço aberto para experimentação na criação de documentários potenciais
logo: https://pocketdocs.com.br/assets/img/pocket-v0.png
image: https://pocketdocs.com.br/assets/img/pocket-v0.png
